Added new command "config"
infinimesh/inf pull request #11
Opened 2024-02-07 22:45 UTC by dimquaa

2024-02-08 07:03 UTC, gorobot-nz approved these changes

2024-02-08 10:47 UTC, slntopp requested changes

2024-02-08 10:47 UTC, slntopp commented on cmd/devices.go
> +	RunE: func(cmd *cobra.Command, args []string) error {
Add arts length validation

2024-02-08 10:47 UTC, slntopp commented on cmd/devices.go
> +	Use:   "config",
Document the arguments in "use" section
See other commands

2024-02-08 10:51 UTC, dimquaa commented on cmd/devices.go
> +	RunE: func(cmd *cobra.Command, args []string) error {
do you mean args ?

2024-02-08 10:56 UTC, dimquaa commented on cmd/devices.go
> +	RunE: func(cmd *cobra.Command, args []string) error {
check length of the incoming uuid?

2024-02-08 15:42 UTC, slntopp commented on cmd/devices.go
> +	RunE: func(cmd *cobra.Command, args []string) error {
There is a Args field in `cobra.Command` where you can supply cobra validation func, which would check the length. So you don't need to do `if len(...) {...}` youself

2024-02-13 09:40 UTC, slntopp approved these changes

2024-02-13 09:40 UTC, merged